### ISSUE TITLE
这个仓库看起来似乎很屌啊

### ISSUE THREAD

**Issue by SmacUL** [symphony09/running#1]

**Comment by biningo** [comment]
Hi，这么屌的项目还继续开发吗？: ) @symphony09

**Comment by symphony09** [comment]
可以关注下 symphony09/ograph: 【Go DAG Schedule Framework】A simple way to build a pipeline with Go. (github.com) 

OGraph 结合了 running 以及同类 C++ 优秀项目 CGraph 的优点，改掉了不少一开始闭门造车留下的别扭设计

保持简单，并且更完善更快速，如果你喜欢running 这个项目的话，我想你也一定会喜欢 OGraph




一言总之，后续会把精力花在新的 OGraph 这个项目上，欢迎提出意见，互相学习交流 : )



















在 2024-05-12 21:54:03，"wuyue" ***@***.***> 写道：

Hi，这么屌的项目还继续开发吗？: ) @symphony09

**Comment by biningo** [comment]
Ok, I have given star. Thank you for your work! ❤️
